### ISSUE TITLE
Part Sourcing

### ISSUE THREAD

**Issue by bmartin598** [td0g/ballistic_chronograph_mk2#1]
Hello,

I am working on sourcing parts for the Lightgate PCB. The Schottky Barrier Diode you have in the BOM pulls up two different ones. Your digikey and manufacturer part number return 1 diode (which has been discontinued) and your LCSC part number pulls up a different one. Will the LCSC part work? It has a different package call out and don't know if it would fit.

Thanks

**Comment by TheAxeDude** [comment]
@bmartin598  what was your resolution here? Doing the same thing now
